"""add unique constraint to hotel

Revision ID: 44e3a75e44e7
Revises: 5776426f7a99
Create Date: 2026-01-19 20:39:48.962910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e3a75e44e7'
down_revision: Union[str, None] = '5776426f7a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_hotels_name_location', 'hotels', ['name', 'location'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_hotels_name_location', 'hotels', type_='unique')
    # ### end Alembic commands ###
