"""add stars to hotels

Revision ID: 5776426f7a99
Revises: ce85f7241f61
Create Date: 2026-01-18 18:07:15.500723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5776426f7a99'
down_revision: Union[str, None] = 'ce85f7241f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('stars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'stars')
    # ### end Alembic commands ###
